// Unit tests puros (sin pool Workers / Hyperdrive).
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'src/helpers/dte/**/*.test.js',
      'src/helpers/env-isolation.test.js',
      'src/api/guias-despacho.test.js',
      'src/api/dashboard-executive-kpis.test.js',
      'src/helpers/security-headers.test.js',
      'src/helpers/optimizer-flota.test.js',
      'src/helpers/dead-man-switch.test.js',
      'src/helpers/mapbox-directions.test.js',
      'src/api/route-geometry.test.js',
      'src/helpers/recalcular-ruteo.test.js',
      'src/api/recalcular-ruteo.test.js',
      'src/helpers/vrp-solver.test.js',
      'src/helpers/perfil-pesos.test.js',
      'src/helpers/geocode.test.js',
      'src/helpers/bitacora-insert.test.js',
      'src/helpers/trip-ownership.test.js',
      'src/helpers/tower-poll-cache.test.js',
      'src/helpers/pod-requirements.test.js',
      'src/helpers/wms-stock.test.js',
      'src/utils.test.js',
      'src/helpers/midday-reopt.test.js',
      'src/helpers/cargo-constraints.test.js',
      'src/api/driver-auth-hardening.test.js',
      'src/monitoring/errors.test.js',
      'src/monitoring/meta-health.test.js',
      'src/api/order-ingest-webhook.test.js',
      'src/api/platform-ingest-webhook.test.js',
      'src/queues.smoke.test.js',
      'src/helpers/safe-remote-fetch.test.js',
      'src/api/asignar-chofer.test.js',
      'src/index.rate-limit-wiring.smoke.test.js',
      'src/monitoring/queue-middleware.test.js',
      'src/jobs.dead-man-switch.test.js',
      'src/helpers/scan-token.test.js',
      'src/helpers/pin-kdf.test.js',
      'src/api/gps-live.test.js',
      'src/api/bodega.test.js',
      'src/helpers/operator-auth.test.js',
      'src/api/operator-login.test.js',
      'src/erp/erp.test.js',
      'src/erp/produccion.test.js',
    ],
  },
});

